[package]
name = "neils_form_spellchecker"
version = "0.2.0"
authors = ["Thomas Hurst <tom@hur.st>"]

[dependencies]
select = "0.4"
mailparse = "0.6"
ispell = "0.3.0"
lettre = "0.9"
lettre_email = "0.9"
base64 = "0.10"
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"
