[package]
name = "neils_form_spellchecker"
version = "0.1.0"
authors = ["Thomas Hurst <tom@hur.st>"]

[dependencies]
select = "0.4.2"
mailparse = "0.6.2"
ispell = "0.3.0"
lettre = "0.8.2"
lettre_email = "0.8.2"
base64 = "0.9.2"
serde = "1.0.76"
serde_derive = "1.0.76"
toml = "0.4.6"
